### PR TITLE
Fix user stories

### LINKED ISSUE #25: Fix the user stories & use cases according to Week 7 Tutorial
Hi @nguyendqminh 

Can you take a look at the current user stories & use cases to see if there is anything to improve/fix according to the Week 7 Tutorial? Add more obvious and essential user stories? 

@simonteozw can you help Minh verify this after he is done?

Thanks

### PR DESCRIPTION
**Pull request by nguyendqminh**

### CODE REVIEW

**Review by UncleGrandpa925 — CHANGES_REQUESTED** [review]
Dear Minh 

Currently there is one 1 use case, can you add more use case for our app? I think for v1.2 we have already proposed quite a number of features

Also, can you check again to see if there is any obvious user storie missing? 

Thank you

**Comment by UncleGrandpa925** [comment]
@nguyendqminh can you take a look at my message above and provide me the deadline that you will resolve this? Thank you!

**Comment by nguyendqminh** [comment]
> Dear Minh
> 
> Currently there is one 1 use case, can you add more use case for our app? I think for v1.2 we have already proposed quite a number of features
> 
> Also, can you check again to see if there is any obvious user storie missing?
> 
> Thank you

Noted, I am working on it now. Will get this done by tomorrow (Tuesday) 6pm.

**Comment by UncleGrandpa925** [comment]
@nguyendqminh Hi, any updates on this?

**Pull request closed without merging**
